#!/usr/bin/env bash
set -Eeuo pipefail
#配置左右相机
#运行：v4l2-ctl --list-device
RULE_FILE="/etc/udev/rules.d/99-hbvcam.rules"
#在下面修改
LEFT_ID_PATH_DEFAULT="pci-0000:00:14.0-usb-0:2:1.0"
RIGHT_ID_PATH_DEFAULT="pci-0000:00:14.0-usb-0:3:1.0"

LEFT_ID_PATH="${LEFT_ID_PATH:-${LEFT_ID_PATH_DEFAULT}}"
RIGHT_ID_PATH="${RIGHT_ID_PATH:-${RIGHT_ID_PATH_DEFAULT}}"

usage() {
    cat <<'EOF'
Usage: bash scripts/setup_hbvcam_udev.sh [options]

Options:
  --left-id ID_PATH      USB ID_PATH for the left HBVCAM
  --right-id ID_PATH     USB ID_PATH for the right HBVCAM
  -h, --help             Show this help

The values can also be supplied through LEFT_ID_PATH and RIGHT_ID_PATH.

Inspect the index-0 capture nodes before setup:
  v4l2-ctl --list-devices
  udevadm info -q property -n /dev/videoN | grep -E '^(ID_PATH|ID_V4L_PRODUCT)='
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --left-id)
            [[ $# -ge 2 ]] || { echo "[ERROR] Missing value for --left-id" >&2; exit 2; }
            LEFT_ID_PATH="$2"
            shift 2
            ;;
        --right-id)
            [[ $# -ge 2 ]] || { echo "[ERROR] Missing value for --right-id" >&2; exit 2; }
            RIGHT_ID_PATH="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "[ERROR] This setup script must be run on Linux." >&2
    exit 1
fi
if [[ "${LEFT_ID_PATH}" == "${RIGHT_ID_PATH}" ]]; then
    echo "[ERROR] Left and right ID_PATH values must be different." >&2
    exit 1
fi
command -v udevadm >/dev/null 2>&1 || {
    echo "[ERROR] udevadm was not found." >&2
    exit 1
}
command -v v4l2-ctl >/dev/null 2>&1 || {
    echo "[ERROR] v4l2-ctl was not found. Install v4l-utils first." >&2
    exit 1
}
command -v sudo >/dev/null 2>&1 || {
    echo "[ERROR] sudo was not found." >&2
    exit 1
}

echo "[INFO] Rule file : ${RULE_FILE}"
echo "[INFO] Left path : ${LEFT_ID_PATH}"
echo "[INFO] Right path: ${RIGHT_ID_PATH}"

sudo tee "${RULE_FILE}" >/dev/null <<EOF
# Auto-generated by setup_hbvcam_udev.sh
SUBSYSTEM=="video4linux", KERNEL=="video*", ENV{ID_PATH}=="${LEFT_ID_PATH}", ATTR{index}=="0", SYMLINK+="cam_left"
SUBSYSTEM=="video4linux", KERNEL=="video*", ENV{ID_PATH}=="${RIGHT_ID_PATH}", ATTR{index}=="0", SYMLINK+="cam_right"
EOF

echo "[INFO] Reloading udev rules..."
sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=video4linux
sudo udevadm settle

echo "[INFO] Stable camera links:"
for link in /dev/cam_left /dev/cam_right; do
    if [[ -e "${link}" ]]; then
        ls -l "${link}"
    else
        echo "[WARN] ${link} does not exist yet. Reconnect the corresponding camera."
    fi
done

if [[ -e /dev/cam_left && -e /dev/cam_right ]]; then
    left_target="$(readlink -f /dev/cam_left)"
    right_target="$(readlink -f /dev/cam_right)"
    if [[ "${left_target}" == "${right_target}" ]]; then
        echo "[ERROR] Both stable links resolve to ${left_target}. Check the ID_PATH values." >&2
        exit 1
    fi
    echo "[DONE] HBVCAM udev setup complete."
else
    echo "[WARN] Rules were installed, but one or more cameras need to be reconnected."
fi
